<a href="https://colab.research.google.com/github/thegurdian/ML/blob/main/Activation_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ReLU activation function


In [1]:
import numpy as np



def relu(x):
  return np.maximum(0,x)

relu(np.array([-2,10,4,6]))

array([ 0, 10,  4,  6])

Leaky ReLU Function

In [2]:
def leaky_relu(x,alpha=0.01):
  return np.where(x>0,x,alpha*x)

leaky_relu(np.array([-19,2,3,4]))

array([-0.19,  2.  ,  3.  ,  4.  ])

# ELU

In [3]:
def ELU(x,alpha=0.01):
  return np.where(x>0,x,alpha *(np.exp(x)-1))
ELU(np.array([-10,1,2,3]))

array([-0.00999955,  1.        ,  2.        ,  3.        ])

# Sigmoid

In [4]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

x = np.array([-3, -1, 0, 1, 3])

print(sigmoid(x))

[0.04742587 0.26894142 0.5        0.73105858 0.95257413]


# Tanh Function

In [5]:
def tanh(x):
    return np.tanh(x)

x = np.array([-3, -1, 0, 1, 3])

print(tanh(x))

[-0.99505475 -0.76159416  0.          0.76159416  0.99505475]


# Swish

In [6]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def swish(x):
    return x * sigmoid(x)

x = np.array([-3, -1, 0, 2])

print(swish(x))

[-0.14227762 -0.26894142  0.          1.76159416]
