<a href="https://colab.research.google.com/github/thegurdian/ML/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print(np.dot(A, B))
print(A @ B)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [3]:
A = np.array([[1,2],
              [3,4]])

A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [4]:
A = np.array([[2,0],
              [0,3]])

values, vectors = np.linalg.eig(A)
print(values)
print(vectors)

[2. 3.]
[[1. 0.]
 [0. 1.]]
